//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLittleOrangeChannel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAssinaturas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblAssinaturas()
        {
            this.tblParcelas = new HashSet<tblParcelas>();
        }
    
        public int idAssinatura { get; set; }
        public int idPrestador { get; set; }
        public int idCanal { get; set; }
        public int idAbrangencia { get; set; }
        public int idStatus { get; set; }
        public Nullable<System.DateTime> dtInicio { get; set; }
        public Nullable<System.DateTime> dtTermino { get; set; }
        public Nullable<decimal> ValorContrato { get; set; }
        public Nullable<int> DiaPagamento { get; set; }
        public string Log { get; set; }
    
        public virtual tblDominios tblDominios { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
        public virtual tblPrestador tblPrestador { get; set; }
        public virtual tblStatus tblStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblParcelas> tblParcelas { get; set; }
    }
}
