//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLittleOrangeChannel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPrestadorBase
    {
        public int idPrestador { get; set; }
        public int idCondominio { get; set; }
        public int idCanal { get; set; }
        public string Empresa { get; set; }
        public string Email { get; set; }
        public string Celular { get; set; }
        public string CPF_CNPJ { get; set; }
        public int idEspecialidade { get; set; }
        public int idStatus { get; set; }
        public Nullable<System.DateTime> dtCriacao { get; set; }
    
        public virtual tblCondominio tblCondominio { get; set; }
        public virtual tblEspecialidade tblEspecialidade { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
        public virtual tblStatus tblStatus { get; set; }
    }
}
