//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLittleOrangeChannel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPrestador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPrestador()
        {
            this.tblAssinaturas = new HashSet<tblAssinaturas>();
            this.tblAvaliacao = new HashSet<tblAvaliacao>();
            this.tblCliques = new HashSet<tblCliques>();
            this.tblParcelas = new HashSet<tblParcelas>();
            this.tblPrestadorEspecialidade = new HashSet<tblPrestadorEspecialidade>();
        }
    
        public int idPrestador { get; set; }
        public int idCondominio { get; set; }
        public int idCanal { get; set; }
        public int idAbrangencia { get; set; }
        public string Empresa { get; set; }
        public string Endereco { get; set; }
        public string Complemento { get; set; }
        public string Bairro { get; set; }
        public string Cidade { get; set; }
        public string UF { get; set; }
        public string Pais { get; set; }
        public string CEP { get; set; }
        public string CodigoIBGE { get; set; }
        public string Email { get; set; }
        public string Celular { get; set; }
        public string CPF_CNPJ { get; set; }
        public string Fone { get; set; }
        public Nullable<decimal> Latitude { get; set; }
        public Nullable<decimal> Longitude { get; set; }
        public Nullable<int> QtdeAvaliacao { get; set; }
        public Nullable<decimal> NotaAvaliacao { get; set; }
        public int idStatus { get; set; }
        public Nullable<int> Numero { get; set; }
        public Nullable<int> idPlano { get; set; }
        public Nullable<int> idFormaPagto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAssinaturas> tblAssinaturas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblAvaliacao> tblAvaliacao { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblCliques> tblCliques { get; set; }
        public virtual tblCondominio tblCondominio { get; set; }
        public virtual tblDominios tblDominios { get; set; }
        public virtual tblDominios tblDominios1 { get; set; }
        public virtual tblDominios tblDominios2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblParcelas> tblParcelas { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPrestadorEspecialidade> tblPrestadorEspecialidade { get; set; }
        public virtual tblStatus tblStatus { get; set; }
    }
}
