//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLittleOrangeChannel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPlano_Abrangencia
    {
        public int idPlanoAbrangencia { get; set; }
        public int idPlano { get; set; }
        public int idAbrangencia { get; set; }
        public System.DateTime dataCriacao { get; set; }
        public string codPlano { get; set; }
        public string linkPagSeguro { get; set; }
        public Nullable<decimal> valor { get; set; }
        public string Log { get; set; }
        public int idStatus { get; set; }
    
        public virtual tblDominios tblDominios { get; set; }
        public virtual tblDominios tblDominios1 { get; set; }
        public virtual tblStatus tblStatus { get; set; }
    }
}
