//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLittleOrangeChannel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblParcelas
    {
        public int idParcela { get; set; }
        public int idAssinatura { get; set; }
        public int idPrestador { get; set; }
        public System.DateTime dataVencimento { get; set; }
        public Nullable<System.DateTime> dataPagamento { get; set; }
        public decimal valorDevido { get; set; }
        public Nullable<decimal> valorPago { get; set; }
        public string Log { get; set; }
        public int idStatus { get; set; }
    
        public virtual tblAssinaturas tblAssinaturas { get; set; }
        public virtual tblPrestador tblPrestador { get; set; }
        public virtual tblStatus tblStatus { get; set; }
    }
}
