//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLittleOrangeChannel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUsuarioPerfil
    {
        public int idUsuario { get; set; }
        public int idPerfil { get; set; }
        public int idStatus { get; set; }
        public Nullable<System.DateTime> dtValidade { get; set; }
    
        public virtual tblPerfil tblPerfil { get; set; }
        public virtual tblStatus tblStatus { get; set; }
        public virtual tblUsuario tblUsuario { get; set; }
    }
}
