//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheLittleOrangeChannel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_EspecialidadeCondominioCidade
    {
        public int idCondominio { get; set; }
        public string codigoIBGE { get; set; }
        public string Nome { get; set; }
        public string Empresa { get; set; }
        public string Descricao { get; set; }
        public string Icone { get; set; }
    }
}
